spring:
 profiles:
 active:
 - dev
---
spring:
 profiles: dev #开发环境
 application: 
  name: test-SpringCloud-config-lingdu-dev
---
spring:
 profiles: test #测试环境
 application:
 name: test-SpringCloud-config-lingdu-test